apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-1-app
  namespace: argocd
spec:
  project: team-1
  source:
    repoURL: https://github.com/abhishekmaniy/multi-tanant-deployment.git
    targetRevision: HEAD
    path: team-1
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: node-1
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    
    automated:
      selfHeal: true
      prune: true