apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-1
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/abhishekmaniy/multi-tanant-deployment.git
  destinations:
    - namespace: node-1
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
